export const API_ROUTES = {
    GET_PASSWORD: "/password.get",
    VERIFY_PASSWORD: "/password.verify",
    MYDATA: "/mydata",
    LOGOUT: "/logout",
    METHODIC_SAVE: "/methodic.save",
    METHODIC_GET: "/methodic.get",
    METHODICS_ALL: "/methodic.all",
    METHODIC_REMOVE: "/methodic.remove",
    RESEARCH_SAVE: "/research.save",
    RESEARCH_GET: "/research.get",
    RESEARCHES_ALL: "/research.all",
    RESEARCH_REMOVE: "/research.remove",
    RESEARCH_PUBLISH: "/research.publish",
    RESEARCH_UNPUBLISH: "/research.unpublish",
    RESEARCH_RESPONDENT: "/research.respondent.get",
    RESPONDENT_SEND: "/respondent.send",
    RESPONDENTS: "/respondent.get",
    GROUPS: "/group.get",
    GROUP_CREATE: "/group.create",
    GROUP_REMOVE: "/group.remove"
}